### ISSUE TITLE
Linux Anaconda pySDC environment bug

### ISSUE THREAD

**Issue by Krissmedt** [Parallel-in-Time/pySDC#101]
Running a Conda environment in Linux terminal, all dependencies installed without issue. Running 'spiraling_particle_playground.py' throws the following error for the progressbar:

(pySDC) [---User and PC name dedacted--- Boris]$ python spiraling_particle_playground.py 
controller - WARNING: classic controller is about to become deprecated, use multigrid controller instead
Traceback (most recent call last):
  File "spiraling_particle_playground.py", line 110, in <module>
    uinit, stats, a0 = main(dt=0.01, Tend=1)
  File "spiraling_particle_playground.py", line 68, in main
    uend, stats = controller.run(u0=uinit, t0=t0, Tend=Tend)
  File "/home/csunix/mn12kms/.conda/envs/pySDC/lib/python3.7/site-packages/pySDC/implementations/controller_classes/allinclusive_classic_nonMPI.py", line 96, in run
    self.hooks.pre_run(step=S, level_number=0)
  File "/home/csunix/mn12kms/.conda/envs/pySDC/lib/python3.7/site-packages/pySDC/playgrounds/Boris/spiraling_particle_HookClass.py", line 30, in pre_run
    self.bar_run = progressbar.ProgressBar(max_value=progressbar.UnknownLength)
TypeError: __init__() got an unexpected keyword argument 'max_value'

**Comment by pancetta** [comment]
Hm, well, looks like the ProgressBar changed the way init() is called. I used the spiraling particle problem to test the ProgressBar module, but did not remove it yet. You can either remove all references to ProgressBar in the hook class or ignore the hook class itself by removing [this line](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/playgrounds/Boris/spiraling_particle_playground.py#L39).
