### ISSUE TITLE
Problem with Penningtrap playground

### ISSUE THREAD

**Issue by BlackCat07** [Parallel-in-Time/pySDC#95]
When trying to run the **penningtrap_playground.py** I get the following:

Traceback (most recent call last):
  File ".../pySDC-2.1/playgrounds/Boris/penningtrap_playground.py", line 89, in <module>
    main()
  File ".../pySDC-2.1/playgrounds/Boris/penningtrap_playground.py", line 72, in main
    uend, stats = controller.run(u0=uinit, t0=t0, Tend=Tend)
  File ".../pySDC-2.1/pySDC/implementations/controller_classes/allinclusive_classic_nonMPI.py", line 80, in run
    self.hooks.pre_run(step=S, level_number=0)
  File ".../pySDC-2.1/playgrounds/Boris/penningtrap_HookClass.py", line 46, in pre_run
    N = L.prob.nparts
_AttributeError: 'penningtrap' object has no attribute 'nparts'_

**Comment by pancetta** [comment]
Odd.. but I can reproduce this. I'm on it!
